#!/bin/bash

rm -rf build && mkdir build && cd build || exit
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j 3
sudo install -c -d /usr/local/bin
sudo install -c ts /usr/local/bin
sudo install -c -d /usr/local/share/man/man1
sudo install -c -m 644 ../ts.1 /usr/local/share/man/man1
