#!/bin/sh

# This should create a debian package. First try. Never done before!

version=0.5.4

make install PREFIX=deb/usr
cd deb

# data.tar.gz
tar c --owner root --group root -v -z -f pkg/data.tar.gz usr

# control.tar.gz
find usr/  -type f | xargs md5sum > pkg/DEBIAN/md5sums

dpkg -b pkg

mv pkg.deb ts_${version}_i386.deb
